// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sXIfH0oZtIUZl4oB4ZNUX37ZgJ-IydM',
    appId: '1:1020597730570:web:6bd4f30e381bcf0ea90ef3',
    messagingSenderId: '1020597730570',
    projectId: 'kagyokanri-a2739',
    authDomain: 'kagyokanri-a2739.firebaseapp.com',
    storageBucket: 'kagyokanri-a2739.appspot.com',
    measurementId: 'G-B4SXMW7BPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrV32BFmkeoBt4K4xPD4hzEj7x4wFFhY',
    appId: '1:1020597730570:android:063191a75899ecb3a90ef3',
    messagingSenderId: '1020597730570',
    projectId: 'kagyokanri-a2739',
    storageBucket: 'kagyokanri-a2739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiysWmgPnuUkdKK7ADqzt6PbZANpm_caA',
    appId: '1:1020597730570:ios:57f9e4c932d6e9a6a90ef3',
    messagingSenderId: '1020597730570',
    projectId: 'kagyokanri-a2739',
    storageBucket: 'kagyokanri-a2739.appspot.com',
    iosBundleId: 'com.YogaSchoolKailas.kagyoKanri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiysWmgPnuUkdKK7ADqzt6PbZANpm_caA',
    appId: '1:1020597730570:ios:e70d73e54e1b93c1a90ef3',
    messagingSenderId: '1020597730570',
    projectId: 'kagyokanri-a2739',
    storageBucket: 'kagyokanri-a2739.appspot.com',
    iosBundleId: 'com.YogaSchoolKailas.kagyoKanri.RunnerTests',
  );
}
